environment: production
namespace: prd
app: prd-employees
container:
  name: prd-employees-php
  port: 9000
  image: mboulgoudan/arm64v8-php8.3fpm
  tag: 8.3fpm
  imagePullPolicy: "IfNotPresent"
  containerSecurityContext:
    runAsUser: 1001
    runAsNonRoot: true
  podSecurityContext:
    fsGroup: 1001
replicas: 1
pvc:
  volume: app-persistent-volume
  path: /var/www/html
  claim: app-pv-claim
 