environment: production
namespace: prd
app: prd-employees
replicas: 1
container:
  name: prd-employees-mysql
  port: 3306
  image: arm64v8/mysql
  tag: 8.3
  imagePullPolicy: "IfNotPresent"
  containerSecurityContext:
    runAsUser: 1001
    runAsNonRoot: true
  podSecurityContext:
    fsGroup: 1001
db:
  name: prd-employees
  rootpassword: rootpassword
  user: user
  userpassword: password
pvc:
  volume: mysql-pv
  permissions: mysql-pv-permissions
  path: /data/mysql-volume
  claim: mysql-pv-claim